### PR TITLE
Initial Travis with CPP coverage.

### PR DESCRIPTION
**Pull request by thomasuster**
This just needs you guys to enable travis for msignal. I'll do other PRs for JS, AS3, etc.

### CODE REVIEW

**Comment by thomasuster** [comment]
bump

**Comment by thomasuster** [comment]
bump

**Comment by dpeek** [comment]
We've already got C++ tests running in our own CI environment. They were disabled for some reason on TeamCity but are running again on our new server.

**Comment by thomasuster** [comment]
Oh cool, thanks Dave. If you feel like exposing the badge I think that would make PR process smoother. http://blog.jetbrains.com/teamcity/2012/07/teamcity-build-status-icon/

**Pull request closed without merging**
